import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { AppScreen, Card, PageHeader, PrimaryButton, SecondaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { buildConditionNotes, dominantCondition, parseConditionNotes, statusIdByName, type CachedInventoryRecord, type ConditionCountInput } from "@/features/assetx/domain";
import { getStatuses } from "@/features/assetx/api";
import { getStoredSnapshot, queueInventoryMutation } from "@/features/assetx/offline-store";

/** خانات التفصيل: اسم الحالة كما في خادم AssetX + تسمية عربية للعرض. */
const CONDITION_FIELDS: { label: string; statusName: string; placeholder: string }[] = [
  { label: "جديد / سليم", statusName: "New", placeholder: "0" },
  { label: "يحتاج صيانة", statusName: "Needs Maintenance", placeholder: "0" },
  { label: "تالف", statusName: "Damaged", placeholder: "0" },
];

export default function RecordScreen() {
  const router = useRouter(); const { cycleId, recordId } = useLocalSearchParams<{ cycleId: string; recordId: string }>(); const [record, setRecord] = useState<CachedInventoryRecord | null>(null); const [quantity, setQuantity] = useState(""); const [conditionCounts, setConditionCounts] = useState<string[]>(["", "", ""]); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false);
  const refresh = useCallback(async () => { const item = (await getStoredSnapshot(String(cycleId)))?.records.find((value) => value.record_id === String(recordId)) ?? null; setRecord(item); if (item) { setQuantity(String(item.actual_quantity ?? item.expected_quantity ?? 1)); const parsed = parseConditionNotes(item.notes); setNotes(parsed.restNotes ?? ""); const next = ["", "", ""]; for (const count of parsed.counts) { const index = CONDITION_FIELDS.findIndex((field) => field.statusName.toLowerCase() === count.statusName.trim().toLowerCase()); if (index >= 0 && count.quantity != null) next[index] = String(count.quantity); } setConditionCounts(next); } }, [cycleId, recordId]); useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function save(actualQuantity: number, conditionCountsInput: ConditionCountInput[]) {
    if (!record || !Number.isFinite(actualQuantity) || actualQuantity < 0) return Alert.alert("الكمية غير صحيحة", "أدخل رقماً صفراً أو أكبر.");
    const breakdown = buildConditionNotes(conditionCountsInput);
    const sum = conditionCountsInput.reduce((total, item) => total + (item.quantity ?? 0), 0);
    if (breakdown && sum !== actualQuantity) return Alert.alert("مجموع الحالات لا يطابق", `مجموع الخانات هو ${sum} لكن الكمية الفعلية ${actualQuantity}. عدّل الخانات حتى يتطابق المجموع.`);
    setSaving(true);
    try {
      let actualStatusId: string | null = null;
      try {
        const statuses = await getStatuses();
        actualStatusId = statusIdByName(statuses, dominantCondition(conditionCountsInput));
      } catch { /* دون اتصال: تُرسل الكمية والملاحظات فقط، ويبقى للمراجع تحديث الحالة لاحقاً */ }
      const combinedNotes = breakdown ? (notes.trim() ? `${notes.trim()}\n${breakdown}` : breakdown) : (notes.trim() || null);
      await queueInventoryMutation(String(cycleId), record.record_id, { actual_quantity: actualQuantity, actual_location_id: record.actual_location_id ?? record.expected_location_id, actual_status_id: actualStatusId, notes: combinedNotes });
      router.back();
    } catch { Alert.alert("تعذر الحفظ", "تعذر حفظ النتيجة محلياً على الهاتف."); } finally { setSaving(false); }
  }
  if (!record) return <AppScreen><PageHeader title="تفاصيل الأصل" action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.missing}><Text style={styles.missingText}>لم يُعثر على هذا السجل في الدورة المحفوظة.</Text></View></AppScreen>;
  const inputQuantity = Number(quantity);
  const conditionInputs: ConditionCountInput[] = CONDITION_FIELDS.map((field, index) => ({ statusName: field.statusName, quantity: conditionCounts[index]?.trim() === "" ? null : Number(conditionCounts[index]) }));
  return <AppScreen scroll><PageHeader title="تفاصيل الأصل" subtitle={record.asset_code} action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.content}><Card style={styles.card}><StatusBadge label={record.sync_state === "pending" ? "بانتظار المزامنة" : record.sync_state === "conflict" ? "يحتاج مراجعة" : "محفوظ"} tone={record.sync_state === "pending" ? "amber" : record.sync_state === "conflict" ? "red" : "green"} /><Text style={styles.name}>{record.asset_name}</Text><View style={styles.info}><Text style={styles.value}>{record.expected_location_path ?? record.expected_location ?? "غير محدد"}</Text><Text style={styles.label}>الموقع المتوقع</Text></View><View style={styles.info}><Text style={styles.value}>{record.expected_quantity ?? "—"}</Text><Text style={styles.label}>الكمية المتوقعة</Text></View></Card><Card style={styles.card}><Text style={styles.sectionTitle}>نتيجة الجرد</Text><Text style={styles.label}>الكمية الفعلية</Text><TextInput value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad" style={styles.quantity} textAlign="right" /><Text style={styles.sectionSmall}>تفصيل الكمية حسب الحالة (اختياري — المجموع يجب أن يطابق الكمية)</Text><View style={styles.conditionRow}>{CONDITION_FIELDS.map((field, index) => <View key={field.statusName} style={styles.conditionCell}><Text style={styles.conditionLabel}>{field.label}</Text><TextInput value={conditionCounts[index]} onChangeText={(value) => { const next = [...conditionCounts]; next[index] = value.replace(/[^0-9]/g, ""); setConditionCounts(next); }} keyboardType="number-pad" placeholder={field.placeholder} placeholderTextColor="#94A3B8" style={styles.conditionInput} textAlign="center" /></View>)}</View><Text style={styles.label}>ملاحظة ميدانية اختيارية</Text><TextInput value={notes} onChangeText={setNotes} multiline numberOfLines={3} placeholder="مثال: يحتاج مراجعة الموقع قبل إنشاء طلب نقل" placeholderTextColor="#94A3B8" style={styles.notes} textAlign="right" /></Card><PrimaryButton title="حفظ نتيجة الجرد" icon="save" loading={saving} onPress={() => void save(inputQuantity, conditionInputs)} /><SecondaryButton title="تحديد موقع فعلي واقتراح نقل" icon="swap-horiz" disabled={saving} onPress={() => router.push(`/inventory/${cycleId}/record/${recordId}/location`)} /><PrimaryButton title="تسجيل الأصل غير موجود" icon="remove-circle-outline" tone="red" disabled={saving} onPress={() => void save(0, [])} /><Text style={styles.notice}>اقتراح النقل يُرسل بانتظار الاعتماد فقط؛ لا يتغير موقع الأصل الرئيسي تلقائياً من الهاتف.</Text></View></AppScreen>;
}
const styles = StyleSheet.create({ back: { padding: 8 }, content: { padding: 20, gap: 15 }, card: { gap: 11 }, name: { color: colors.slate, fontSize: 20, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, sectionTitle: { color: colors.slate, fontWeight: "900", fontSize: 17, textAlign: "right", writingDirection: "rtl" }, sectionSmall: { color: colors.muted, fontSize: 12, textAlign: "right", writingDirection: "rtl", marginTop: -3 }, info: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, label: { color: colors.muted, fontSize: 13, fontWeight: "700", textAlign: "right", writingDirection: "rtl" }, value: { flex: 1, color: colors.slate, textAlign: "left", writingDirection: "rtl" }, quantity: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 13, color: colors.slate, fontSize: 18 }, conditionRow: { flexDirection: "row", gap: 8 }, conditionCell: { flex: 1, gap: 6 }, conditionLabel: { color: colors.slate, fontSize: 12, fontWeight: "700", textAlign: "center", writingDirection: "rtl" }, conditionInput: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 12, color: colors.slate, fontSize: 16 }, notes: { minHeight: 88, borderWidth: 1, borderColor: colors.border, borderRadius: 13, padding: 13, color: colors.slate, textAlignVertical: "top", writingDirection: "rtl" }, notice: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: "right", writingDirection: "rtl" }, missing: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 }, missingText: { color: colors.muted, textAlign: "center", writingDirection: "rtl" } });
