import { EmptyState, Field, FormButton, PageTitle, StatusBadge, TextInput, dateLabel, statusLabel } from "@/components/EnergyUi";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Edit3, FileUp, LockKeyhole, Send } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

const toTimestamp = (value: string) => new Date(value).getTime();
const toLocalDateTime = (value: Date | string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };
const readBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(file); });
const nextStatus: Record<string, { status: "data_entry" | "validation" | "reviewed" | "approved" | "closed"; label: string } | undefined> = { draft: { status: "data_entry", label: "فتح الإدخال" }, data_entry: { status: "validation", label: "إرسال للتحقق" }, validation: { status: "reviewed", label: "تأكيد المراجعة" }, reviewed: { status: "approved", label: "اعتماد الدورة" }, approved: { status: "closed", label: "إقفال الدورة" } };

function AttachmentLink({ attachment }: { attachment: { id: number; originalName: string; sizeBytes: number } }) {
  const open = trpc.attachments.open.useMutation({ onError: error => toast.error(error.message) });
  return <button type="button" className="flex w-full items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-right text-sm text-teal-700 hover:bg-teal-50" onClick={() => open.mutate({ attachmentId: attachment.id }, { onSuccess: value => window.open(value.url, "_blank", "noopener,noreferrer") })}><bdi>{attachment.originalName}</bdi><span>{Math.ceil(attachment.sizeBytes / 1024)} KB</span></button>;
}

export default function BillingCyclesPage() {
  const utils = trpc.useUtils();
  const cycles = trpc.energy.cycles.list.useQuery();
  const meters = trpc.energy.meters.list.useQuery();
  const sites = trpc.sites.accessible.useQuery();
  const [selectedCycle, setSelectedCycle] = useState("");
  const [selectedSiteId, setSelectedSiteId] = useState("");
  const [editingCycleId, setEditingCycleId] = useState<number | null>(null);
  const [cycleForm, setCycleForm] = useState({ title: "", start: "", end: "" });
  const [meterForm, setMeterForm] = useState({ code: "", name: "", multiplier: "1" });
  const [reading, setReading] = useState({ meterId: "", previous: "", current: "", multiplier: "1", readAt: "" });
  const [invoice, setInvoice] = useState({ number: "", kwh: "", amount: "", issuedAt: "" });
  const current = cycles.data?.find(item => String(item.id) === selectedCycle);
  const attachments = trpc.attachments.list.useQuery({ entityType: "billingCycle", entityId: Number(selectedCycle || 0) }, { enabled: Boolean(selectedCycle) });
  const createCycle = trpc.energy.cycles.create.useMutation({ onSuccess: () => { toast.success("تم إنشاء الدورة."); utils.energy.cycles.list.invalidate(); }, onError: error => toast.error(error.message) });
  const updateCycle = trpc.energy.cycles.update.useMutation({ onSuccess: () => { toast.success("تم حفظ تعديل الدورة."); utils.energy.cycles.list.invalidate(); setEditingCycleId(null); setCycleForm({ title: "", start: "", end: "" }); }, onError: error => toast.error(error.message) });
  const createMeter = trpc.energy.meters.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة العداد."); utils.energy.meters.list.invalidate(); }, onError: error => toast.error(error.message) });
  const addReading = trpc.energy.meters.addReading.useMutation({ onSuccess: () => toast.success("تم حفظ القراءة."), onError: error => toast.error(error.message) });
  const saveInvoice = trpc.energy.invoices.save.useMutation({ onSuccess: () => toast.success("تم حفظ الفاتورة الرسمية."), onError: error => toast.error(error.message) });
  const changeStatus = trpc.energy.cycles.changeStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث الحالة وحفظ سجل التدقيق."); utils.energy.cycles.list.invalidate(); }, onError: error => toast.error(error.message) });
  const upload = trpc.attachments.upload.useMutation({ onSuccess: () => { toast.success("تم رفع المرفق."); attachments.refetch(); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (!selectedSiteId && sites.data?.[0]) setSelectedSiteId(String(sites.data[0].id)); }, [selectedSiteId, sites.data]);
  const submitCycle = (event: FormEvent) => { event.preventDefault(); const payload = { title: cycleForm.title, periodStart: toTimestamp(cycleForm.start), periodEnd: toTimestamp(cycleForm.end) }; editingCycleId ? updateCycle.mutate({ id: editingCycleId, ...payload }) : createCycle.mutate({ ...payload, siteId: selectedSiteId ? Number(selectedSiteId) : undefined }); };
  const beginEdit = (cycle: NonNullable<typeof cycles.data>[number]) => { if (cycle.status === "closed") return; setEditingCycleId(cycle.id); setCycleForm({ title: cycle.title, start: toLocalDateTime(cycle.periodStart), end: toLocalDateTime(cycle.periodEnd) }); };
  const resetCycleForm = () => { setEditingCycleId(null); setCycleForm({ title: "", start: "", end: "" }); };

  return <div className="mx-auto max-w-7xl space-y-6"><PageTitle eyebrow="الفوترة والتحقق" title="دورات الفوترة نصف الشهرية" description="لكل دورة قراءات مستقلة وفاتورة رسمية وحساب تحليلي ومسار مراجعة متسلسل من المسودة إلى الإقفال." />
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card className="border-0 shadow-sm"><CardHeader><CardTitle>سجل الدورات</CardTitle></CardHeader><CardContent>{cycles.isLoading ? <p className="text-sm text-slate-500">جارٍ تحميل الدورات…</p> : !cycles.data?.length ? <EmptyState title="لا توجد دورات بعد" description="ابدأ بإنشاء دورة الفوترة الأولى، ثم أضف القراءة والفاتورة الرسمية." /> : <div className="overflow-x-auto"><table className="w-full min-w-full md:min-w-[620px] text-right text-xs sm:text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="pb-3">الدورة</th><th className="pb-3">الفترة</th><th className="pb-3">الحالة</th><th className="pb-3">الإجراء</th></tr></thead><tbody>{cycles.data.map(cycle => <tr key={cycle.id} className="border-b border-slate-100"><td className="py-4 font-bold"><bdi>{cycle.title}</bdi></td><td className="py-4 text-slate-500">{dateLabel(cycle.periodStart)} — {dateLabel(cycle.periodEnd)}</td><td className="py-4"><StatusBadge status={cycle.status} /></td><td className="py-4"><div className="flex flex-col gap-1 sm:flex-row sm:gap-2"><Button size="sm" variant="outline" onClick={() => setSelectedCycle(String(cycle.id))}>فتح</Button><Button size="sm" variant="outline" disabled={cycle.status === "closed"} onClick={() => beginEdit(cycle)}><Edit3 className="ml-1 h-3.5 w-3.5" />تعديل</Button></div></td></tr>)}</tbody></table></div>}</CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle>{editingCycleId ? "تعديل بيانات الدورة" : "إنشاء دورة جديدة"}</CardTitle><p className="mt-1 text-sm text-slate-500">يمكن تصحيح اسم أو فترة الدورة ما دامت غير مقفلة.</p></CardHeader><CardContent><form className="grid gap-4" onSubmit={submitCycle}>{!editingCycleId && <Field label="الموقع أو الفرع"><Select value={selectedSiteId} onValueChange={setSelectedSiteId}><SelectTrigger><SelectValue placeholder="اختر الموقع" /></SelectTrigger><SelectContent>{sites.data?.map(site => <SelectItem key={site.id} value={String(site.id)}>{site.name}</SelectItem>)}</SelectContent></Select></Field>}<Field label="اسم الدورة"><TextInput required placeholder="دورة النصف الأول — يناير 2026" value={cycleForm.title} onChange={event => setCycleForm({ ...cycleForm, title: event.target.value })} /></Field><Field label="بداية الدورة"><TextInput required type="datetime-local" value={cycleForm.start} onChange={event => setCycleForm({ ...cycleForm, start: event.target.value })} /></Field><Field label="نهاية الدورة"><TextInput required type="datetime-local" value={cycleForm.end} onChange={event => setCycleForm({ ...cycleForm, end: event.target.value })} /></Field><div className="flex gap-2"><FormButton busy={createCycle.isPending || updateCycle.isPending}>{editingCycleId ? "حفظ التعديل" : "إنشاء الدورة"}</FormButton>{editingCycleId ? <Button type="button" variant="outline" onClick={resetCycleForm}>إلغاء</Button> : null}</div></form></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-3"><Card className="border-0 shadow-sm"><CardHeader><CardTitle>إعداد عداد المؤسسة</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={event => { event.preventDefault(); createMeter.mutate({ code: meterForm.code, name: meterForm.name, multiplier: Number(meterForm.multiplier), siteId: selectedSiteId ? Number(selectedSiteId) : undefined }); }}><Field label="الموقع أو الفرع"><Select value={selectedSiteId} onValueChange={setSelectedSiteId}><SelectTrigger><SelectValue placeholder="اختر الموقع" /></SelectTrigger><SelectContent>{sites.data?.map(site => <SelectItem key={site.id} value={String(site.id)}>{site.name}</SelectItem>)}</SelectContent></Select></Field><Field label="رمز العداد"><TextInput required value={meterForm.code} onChange={event => setMeterForm({ ...meterForm, code: event.target.value })} placeholder="MTR-01" /></Field><Field label="اسم العداد"><TextInput required value={meterForm.name} onChange={event => setMeterForm({ ...meterForm, name: event.target.value })} placeholder="عداد المؤسسة الرئيسي" /></Field><Field label="معامل الضرب"><TextInput required type="number" min="0.0001" step="0.0001" value={meterForm.multiplier} onChange={event => setMeterForm({ ...meterForm, multiplier: event.target.value })} /></Field><FormButton busy={createMeter.isPending}>إضافة العداد</FormButton></form></CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle>تسجيل قراءة</CardTitle></CardHeader><CardContent>{!selectedCycle ? <EmptyState title="اختر دورة" description="افتح دورة أولًا لإضافة قراءتها." /> : <form className="grid gap-3" onSubmit={event => { event.preventDefault(); addReading.mutate({ cycleId: Number(selectedCycle), meterId: Number(reading.meterId), previousReading: Number(reading.previous), currentReading: Number(reading.current), multiplier: Number(reading.multiplier), readAt: toTimestamp(reading.readAt) }); }}><Field label="العداد"><Select value={reading.meterId} onValueChange={meterId => setReading({ ...reading, meterId })}><SelectTrigger><SelectValue placeholder="اختر العداد" /></SelectTrigger><SelectContent>{meters.data?.map(meter => <SelectItem key={meter.id} value={String(meter.id)}><bdi>{meter.name}</bdi></SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-3"><Field label="القراءة السابقة"><TextInput required type="number" min="0" value={reading.previous} onChange={event => setReading({ ...reading, previous: event.target.value })} /></Field><Field label="القراءة الحالية"><TextInput required type="number" min="0" value={reading.current} onChange={event => setReading({ ...reading, current: event.target.value })} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="المعامل"><TextInput required type="number" min="0.0001" step="0.0001" value={reading.multiplier} onChange={event => setReading({ ...reading, multiplier: event.target.value })} /></Field><Field label="تاريخ القراءة"><TextInput required type="datetime-local" value={reading.readAt} onChange={event => setReading({ ...reading, readAt: event.target.value })} /></Field></div><FormButton busy={addReading.isPending}>حفظ القراءة</FormButton></form>}</CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle>الفاتورة الرسمية</CardTitle></CardHeader><CardContent>{!selectedCycle ? <EmptyState title="اختر دورة" description="تسجل الفاتورة للدورة المحددة فقط." /> : <form className="grid gap-3" onSubmit={event => { event.preventDefault(); saveInvoice.mutate({ cycleId: Number(selectedCycle), invoiceNumber: invoice.number || undefined, invoiceIssuedAt: invoice.issuedAt ? toTimestamp(invoice.issuedAt) : undefined, officialKwh: invoice.kwh ? Number(invoice.kwh) : undefined, officialAmount: Number(invoice.amount) }); }}><Field label="رقم الفاتورة"><TextInput value={invoice.number} onChange={event => setInvoice({ ...invoice, number: event.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="استهلاك الفاتورة kWh"><TextInput type="number" min="0" value={invoice.kwh} onChange={event => setInvoice({ ...invoice, kwh: event.target.value })} /></Field><Field label="المبلغ الرسمي"><TextInput required type="number" min="0" value={invoice.amount} onChange={event => setInvoice({ ...invoice, amount: event.target.value })} /></Field></div><Field label="تاريخ الإصدار"><TextInput type="datetime-local" value={invoice.issuedAt} onChange={event => setInvoice({ ...invoice, issuedAt: event.target.value })} /></Field><FormButton busy={saveInvoice.isPending}>حفظ الفاتورة</FormButton></form>}</CardContent></Card></div>
    {current ? <Card className="border-0 shadow-sm"><CardHeader className="flex-row items-center justify-between"><div><CardTitle><bdi>{current.title}</bdi></CardTitle><p className="mt-1 text-sm text-slate-500">الحالة الحالية: {statusLabel(current.status)}</p></div>{nextStatus[current.status] ? <Button className="bg-teal-700 hover:bg-teal-800" onClick={() => { const target = nextStatus[current.status]; if (target) changeStatus.mutate({ cycleId: current.id, status: target.status, reason: target.label }); }}><Send className="ml-2 h-4 w-4" />{nextStatus[current.status]?.label}</Button> : null}</CardHeader><CardContent><div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600"><LockKeyhole className="ml-2 inline h-4 w-4 text-teal-700" />لا يمكن تعديل دورة بعد الإقفال، ويُنشئ الاعتماد والإقفال نسخة حساب موثقة في سجل التدقيق.</div><label className="mt-4 flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-600 hover:bg-slate-50"><FileUp className="h-5 w-5 text-teal-700" /><span>إرفاق PDF أو Excel أو Word أو TXT (حتى 5 MB)</span><input className="hidden" type="file" accept=".pdf,.txt,.xlsx,.xls,.doc,.docx" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return toast.error("الحد الأقصى للمرفق 5 MB."); try { upload.mutate({ entityType: "billingCycle", entityId: current.id, originalName: file.name, mimeType: file.type, base64: await readBase64(file) }); } catch { toast.error("تعذر قراءة الملف."); } }} /></label>{attachments.data?.length ? <div className="mt-4 grid gap-2">{attachments.data.map(item => <AttachmentLink key={item.id} attachment={item} />)}</div> : <p className="mt-3 text-sm text-slate-500">لا توجد مرفقات لهذه الدورة.</p>}</CardContent></Card> : null}
  </div>;
}
