/**
 * Audit event catalog — single source of truth for event action keys (10.2).
 * Services must reference these constants, never arbitrary strings.
 */
export const AUDIT_EVENTS = {
  // Authentication
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  // Authorization / Permission
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  // Asset
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_DELETED: 'ASSET_DELETED',
  ASSET_STATUS_CHANGED: 'ASSET_STATUS_CHANGED',
  // Master data
  CATEGORY_DEACTIVATED: 'CATEGORY_DEACTIVATED',
  STATUS_DEACTIVATED: 'STATUS_DEACTIVATED',
  // Movement
  MOVEMENT_CREATED: 'MOVEMENT_CREATED',
  MOVEMENT_APPROVED: 'MOVEMENT_APPROVED',
  MOVEMENT_REJECTED: 'MOVEMENT_REJECTED',
  // Maintenance
  MAINTENANCE_CREATED: 'MAINTENANCE_CREATED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  // Inventory
  INVENTORY_CREATED: 'INVENTORY_CREATED',
  INVENTORY_STARTED: 'INVENTORY_STARTED',
  INVENTORY_CLOSED: 'INVENTORY_CLOSED',
  INVENTORY_RECORD_VERIFIED: 'INVENTORY_RECORD_VERIFIED',
  // Compliance
  COMPLIANCE_WARNING: 'COMPLIANCE_WARNING',
  // Export
  EXPORT_STARTED: 'EXPORT_STARTED',
  EXPORT_COMPLETED: 'EXPORT_COMPLETED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  // Saved Searches
  SAVED_SEARCH_CREATED: 'SAVED_SEARCH_CREATED',
  SAVED_SEARCH_UPDATED: 'SAVED_SEARCH_UPDATED',
  SAVED_SEARCH_DELETED: 'SAVED_SEARCH_DELETED',
  SAVED_SEARCH_EXECUTED: 'SAVED_SEARCH_EXECUTED',
  // Report templates
  REPORT_TEMPLATE_CREATED: 'REPORT_TEMPLATE_CREATED',
  REPORT_TEMPLATE_UPDATED: 'REPORT_TEMPLATE_UPDATED',
  REPORT_TEMPLATE_DELETED: 'REPORT_TEMPLATE_DELETED',
  // AI
  AI_REPORT_SUMMARY_GENERATED: 'AI_REPORT_SUMMARY_GENERATED',
  // API request audit (written by AuditInterceptor)
  API_REQUEST: 'API_REQUEST',
} as const;

export type AuditEventKey = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
