import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, Plus } from "lucide-react";
import type { ReactNode } from "react";

const ltrIsolate = (value: string) => `\u2066${value}\u2069`;
const rtlIsolate = (value: string) => `\u2067${value}\u2069`;
export const money = (value?: number | string | null) => ltrIsolate(`${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(Number(value ?? 0))}\u00A0ر.ي`);
export const quantity = (value?: number | string | null, unit = "kWh") => ltrIsolate(`${new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(Number(value ?? 0))}\u00A0${unit}`);
export const dateLabel = (value?: Date | string | number | null) => value ? rtlIsolate(new Date(value).toLocaleDateString("ar-YE", { year: "numeric", month: "short", day: "numeric" })) : "—";

const statusLabels: Record<string, string> = { draft: "مسودة", data_entry: "إدخال بيانات", validation: "تحقق", reviewed: "مراجعة", approved: "معتمدة", closed: "مقفلة" };
export const statusLabel = (status: string) => statusLabels[status] ?? status;
const statusStyle: Record<string, string> = { draft: "bg-slate-100 text-slate-700", data_entry: "bg-sky-50 text-sky-700", validation: "bg-amber-50 text-amber-700", reviewed: "bg-violet-50 text-violet-700", approved: "bg-emerald-50 text-emerald-700", closed: "bg-slate-800 text-white" };

export function StatusBadge({ status }: { status: string }) { return <Badge className={`${statusStyle[status] ?? "bg-slate-100"} border-0 px-2.5 py-1 font-medium`}>{statusLabel(status)}</Badge>; }
export function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="relative flex flex-col gap-5 overflow-hidden rounded-[1.75rem] border border-border bg-card/85 px-5 py-5 shadow-[0_10px_32px_rgba(15,23,42,.04)] backdrop-blur-sm md:flex-row md:items-end md:justify-between md:px-7"><div className="absolute inset-x-7 bottom-0 h-px bg-gradient-to-l from-transparent via-teal-200/80 to-transparent" /><div className="relative"><p className="text-xs font-bold tracking-[.18em] text-teal-700 dark:text-teal-300">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-foreground">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div><div className="relative">{action}</div></div>; }
export function MetricCard({ label, value, note, icon, tone = "teal" }: { label: string; value: string; note: string; icon: ReactNode; tone?: "teal" | "amber" | "slate" | "rose" }) { const tones = { teal: { stripe: "#0f887f", iconBg: "#ecfdf5", icon: "#0f766e" }, amber: { stripe: "#f4ae16", iconBg: "#fff7df", icon: "#b45309" }, slate: { stripe: "#172554", iconBg: "#eff6ff", icon: "#1e3a8a" }, rose: { stripe: "#e11d48", iconBg: "#fff1f2", icon: "#be123c" } }; const style = tones[tone]; return <Card className="overflow-hidden border-0 bg-card" style={{ border: "1px solid var(--border)", boxShadow: "0 12px 28px rgba(15,23,42,.055)" }}><CardContent className="p-0"><div className="flex h-1.5" style={{ backgroundColor: style.stripe }} /><div className="p-5"><div className="flex items-start justify-between"><p className="text-sm font-medium text-muted-foreground">{label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl" style={{ backgroundColor: style.iconBg, color: style.icon }}>{icon}</span></div><p className="metric-value mt-5 text-2xl font-semibold text-foreground">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div></CardContent></Card>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50/70 px-6 py-12 text-center"><p className="font-bold text-slate-800">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{description}</p></div>; }
export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
export function TextInput(props: React.ComponentProps<typeof Input>) { const numeric = props.type === "number" || props.type === "date" || props.type === "datetime-local"; return <Input className={`h-10 bg-white ${numeric ? "text-left tabular-nums" : ""}`} dir={numeric ? "ltr" : "rtl"} {...props} />; }
export function FormButton({ busy, children }: { busy?: boolean; children: ReactNode }) { return <Button className="h-10 bg-teal-700 px-4 hover:bg-teal-800" disabled={busy}>{busy ? <Loader2 className="ml-2 h-4 w-4 animate-spin" /> : <Plus className="ml-2 h-4 w-4" />}{children}</Button>; }
export function RoleSelect({ value, onValueChange }: { value: string; onValueChange: (value: string) => void }) { const roles = [["energy_operator", "مشغل طاقة"], ["accountant", "محاسب"], ["maintenance", "صيانة"], ["reviewer", "مراجع / مشرف"], ["auditor", "مدقق"], ["management", "إدارة"], ["admin", "مدير النظام"]]; return <Select value={value} onValueChange={onValueChange}><SelectTrigger className="h-9 w-40 bg-white"><SelectValue /></SelectTrigger><SelectContent>{roles.map(([id, label]) => <SelectItem value={id} key={id}>{label}</SelectItem>)}</SelectContent></Select>; }
