import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { AppScreen, EmptyState, PageHeader, PrimaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { createPendingTransferRequest, getEmployees, getLocations, getStatuses } from "@/features/assetx/api";
import { buildConditionNotes, dominantCondition, parseConditionNotes, statusIdByName, type CachedInventoryRecord, type EmployeeOption, type LocationOption, friendlyError } from "@/features/assetx/domain";
import { getStoredSnapshot, queueInventoryMutation } from "@/features/assetx/offline-store";

export default function ActualLocationScreen() {
  const router = useRouter(); const { cycleId, recordId } = useLocalSearchParams<{ cycleId: string; recordId: string }>(); const [record, setRecord] = useState<CachedInventoryRecord | null>(null); const [locations, setLocations] = useState<LocationOption[]>([]); const [employees, setEmployees] = useState<EmployeeOption[]>([]); const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null); const [selected, setSelected] = useState<LocationOption | null>(null); const [query, setQuery] = useState(""); const [reason, setReason] = useState("تم العثور على الأصل في موقع مختلف أثناء الجرد الميداني."); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const snapshot = await getStoredSnapshot(String(cycleId)); setRecord(snapshot?.records.find((item) => item.record_id === String(recordId)) ?? null); setLocations(await getLocations()); } catch (error) { Alert.alert("تعذر تحميل المواقع", friendlyError(error)); } finally { setLoading(false); } try { setEmployees(await getEmployees()); } catch { /* الموظفون اختياريون — لا نعطل إنشاء النقل إن تعذر جلبهم */ } }, [cycleId, recordId]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const available = useMemo(() => { const text = query.trim().toLowerCase(); return locations.filter((location) => location.id !== record?.expected_location_id && (!text || `${location.full_path} ${location.name}`.toLowerCase().includes(text))); }, [locations, query, record?.expected_location_id]);
  function confirmSubmit() {
    if (!record || !selected) return;
    Alert.alert(
      "تأكيد إنشاء اقتراح النقل",
      `من الموقع: ${record.expected_location_path ?? record.expected_location ?? "غير محدد"}\nإلى الموقع: ${selected.full_path}\nالسبب: ${reason.trim() || "اختلاف موقع ميداني"}\n\nبعد التأكيد: يُنشأ طلب نقل بحالة معلقة (pending) فقط. لن يتغير موقع الأصل الرئيسي — يبقى الاعتماد والنقل الفعلي عبر منصة AssetX Web من قِبل الشخص المختص.`,
      [
        { text: "إلغاء", style: "cancel" },
        { text: "تأكيد وإنشاء الاقتراح", onPress: () => void submit() },
      ],
    );
  }
  async function resolveTargetStatusId(): Promise<string | null> {
    if (!record) return null;
    if (record.actual_status_id) return record.actual_status_id;
    const parsed = parseConditionNotes(record.notes);
    const dominant = dominantCondition(parsed.counts);
    if (!dominant) return null;
    try { return statusIdByName(await getStatuses(), dominant); } catch { return null; }
  }
  async function submit() { if (!record || !selected) return; setSubmitting(true); try { const notes = `${reason.trim() || "اختلاف موقع ميداني"}\nالموقع الفعلي: ${selected.full_path}`; const toStatusId = await resolveTargetStatusId(); let sentStatusName: string | null = null; if (toStatusId) { try { sentStatusName = (await getStatuses()).find((s) => s.id === toStatusId)?.name ?? null; } catch { sentStatusName = null; } } await queueInventoryMutation(String(cycleId), record.record_id, { actual_quantity: record.actual_quantity ?? record.expected_quantity ?? 1, actual_location_id: selected.id, actual_employee_id: selectedEmployee?.id ?? null, actual_status_id: toStatusId, notes }); const movement = await createPendingTransferRequest({ asset_id: record.asset_id, from_location_id: record.expected_location_id, to_location_id: selected.id, quantity: record.actual_quantity ?? record.expected_quantity, reason: reason.trim() || "اختلاف موقع ميداني", notes, to_employee_id: selectedEmployee?.id ?? null, to_status_id: toStatusId }); if (movement.status !== "pending") throw new Error("REQUEST_FAILED"); Alert.alert("تم إنشاء اقتراح النقل", `ما أُرسل إلى الخادم:\nالمستلم: ${selectedEmployee?.name ?? "لم يُحدد"}\nالحالة: ${sentStatusName ?? "لم تُحدد"}\n\nالاعتماد عبر AssetX Web فقط — لم يتغير موقع الأصل تلقائياً.`, [{ text: "حسناً", onPress: () => router.back() }]); } catch (error) { Alert.alert("تعذر إنشاء الاقتراح", friendlyError(error)); } finally { setSubmitting(false); } }
  return <AppScreen><PageHeader title="تحديد الموقع الفعلي" subtitle="إنشاء اقتراح نقل بانتظار الاعتماد" action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.top}><StatusBadge label={record?.expected_location_path ?? record?.expected_location ?? "الموقع المتوقع غير محدد"} tone="blue" /><Text style={styles.hint}>اختر الموقع الذي وُجد فيه الأصل فعلياً، ثم اكتب سبباً مختصراً. لن ينقل التطبيق الأصل تلقائياً.</Text><TextInput value={query} onChangeText={setQuery} placeholder="ابحث في المواقع" placeholderTextColor="#94A3B8" style={styles.search} textAlign="right" /><TextInput value={reason} onChangeText={setReason} placeholder="سبب اختلاف الموقع" placeholderTextColor="#94A3B8" style={styles.reason} multiline textAlign="right" />{employees.length ? <View style={styles.employeeSection}><Text style={styles.employeeTitle}>المستلم (اختياري)</Text><View style={styles.employeeRow}>{employees.map((employee) => <Pressable key={employee.id} onPress={() => setSelectedEmployee(selectedEmployee?.id === employee.id ? null : employee)} style={[styles.employeeChip, selectedEmployee?.id === employee.id && styles.employeeChipSelected]}><Text style={[styles.employeeChipText, selectedEmployee?.id === employee.id && styles.employeeChipTextSelected]}>{employee.name}</Text></Pressable>)}</View></View> : null}</View><FlatList data={available} contentContainerStyle={styles.list} keyExtractor={(item) => item.id} ListEmptyComponent={<EmptyState icon="location-off" title={loading ? "يجري تحميل المواقع" : "لا توجد مواقع مطابقة"} detail="تحقق من اتصال Backend أو غيّر عبارة البحث." />} renderItem={({ item }) => <Pressable onPress={() => setSelected(item)} style={({ pressed }) => [styles.row, selected?.id === item.id && styles.rowSelected, pressed && styles.pressed]}><MaterialIcons name={selected?.id === item.id ? "radio-button-checked" : "radio-button-unchecked"} color={selected?.id === item.id ? colors.blue : colors.muted} size={23} /><View style={styles.rowText}><Text style={styles.rowTitle}>{item.full_path}</Text><Text style={styles.rowDetail}>{item.name}</Text></View></Pressable>} /><View style={styles.bottom}><PrimaryButton title="إنشاء اقتراح نقل" icon="swap-horiz" loading={submitting} disabled={!selected || !record || submitting} onPress={confirmSubmit} /></View></AppScreen>;
}
const styles = StyleSheet.create({ back: { padding: 8 }, top: { padding: 16, gap: 10, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: colors.border }, hint: { color: colors.muted, textAlign: "right", lineHeight: 20, writingDirection: "rtl" }, search: { minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 13, color: colors.slate, writingDirection: "rtl" }, reason: { minHeight: 68, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12, color: colors.slate, textAlignVertical: "top", writingDirection: "rtl" }, list: { padding: 16, gap: 10, paddingBottom: 88, flexGrow: 1 }, row: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: "#FFFFFF" }, rowSelected: { borderColor: colors.blue, backgroundColor: colors.blueSoft }, rowText: { flex: 1, alignItems: "flex-end" }, rowTitle: { color: colors.slate, textAlign: "right", fontWeight: "800", writingDirection: "rtl" }, rowDetail: { color: colors.muted, textAlign: "right", marginTop: 3, writingDirection: "rtl" }, pressed: { opacity: 0.8 }, bottom: { position: "absolute", left: 16, right: 16, bottom: 16 }, employeeSection: { gap: 8 }, employeeTitle: { color: colors.slate, fontWeight: "800", fontSize: 14, textAlign: "right", writingDirection: "rtl" }, employeeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, employeeChip: { minHeight: 38, borderRadius: 99, borderWidth: 1, borderColor: colors.border, backgroundColor: "#FFFFFF", paddingHorizontal: 14, alignItems: "center", justifyContent: "center" }, employeeChipSelected: { borderColor: colors.blue, backgroundColor: colors.blueSoft }, employeeChipText: { color: colors.slate, fontWeight: "700", fontSize: 13, writingDirection: "rtl" }, employeeChipTextSelected: { color: colors.blue } });
